name: PR Validation

on:
  pull_request:

jobs:
  fake-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR text
        uses: ogreface/block-if-bad-asana-link@v001
        with:
          sentinel: "fixme.fake.com"
          regex: 'fake.com/\d'
