name: PR Validation

on:
  pull_request:

jobs:
  fake-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR text
        uses: ogreface/block-if-bad-asana-link@v001
        with:
          sentinel: "fixme.addi.com"
          regex: 'https://app.asana.com/\d/\d+/\d+/f'
